name: 'Build and deploy to GCP'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Store build artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: glossary-dist
          retention-days: 2
  deploy:
    continue-on-error: true
    needs: build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
          name: glossary-dist
      - name: GCP Auth
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
      - name: Bashing
        run: |
          ls -al
          ls -al dist
          ls -al dist/glossary
          cat /home/runner/work/glossary/glossary/gha-creds-2*
      - name: App Engine Deploy
        id: deployment
        uses: google-github-actions/deploy-appengine@v2
        with:
          flags: '--verbosity=debug'
      - name: Result
        run: |
          echo ${{ steps.deploy.outputs.url }}

